//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerCampaign.SOAP
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCustomerRewardRq", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.Services.Models.Requests" +
        "")]
    public partial class AddCustomerRewardRq : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int AgentIdField;
        
        private int CustomerIdField;
        
        private int DiscountPercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId
        {
            get
            {
                return this.AgentIdField;
            }
            set
            {
                if ((this.AgentIdField.Equals(value) != true))
                {
                    this.AgentIdField = value;
                    this.RaisePropertyChanged("AgentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                if ((this.CustomerIdField.Equals(value) != true))
                {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                if ((this.DiscountPercentField.Equals(value) != true))
                {
                    this.DiscountPercentField = value;
                    this.RaisePropertyChanged("DiscountPercent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCustomerRewardRs", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.Services.Models.Response" +
        "s")]
    public partial class AddCustomerRewardRs : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ErrorMessageField;
        
        private bool SuccessfulSavingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true))
                {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuccessfulSaving
        {
            get
            {
                return this.SuccessfulSavingField;
            }
            set
            {
                if ((this.SuccessfulSavingField.Equals(value) != true))
                {
                    this.SuccessfulSavingField = value;
                    this.RaisePropertyChanged("SuccessfulSaving");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerCampaign.SOAP.IRewardService")]
    public interface IRewardService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRewardService/AddCustomerReward", ReplyAction="http://tempuri.org/IRewardService/AddCustomerRewardResponse")]
        System.Threading.Tasks.Task<CustomerCampaign.SOAP.AddCustomerRewardRs> AddCustomerRewardAsync(CustomerCampaign.SOAP.AddCustomerRewardRq rq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IRewardServiceChannel : CustomerCampaign.SOAP.IRewardService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class RewardServiceClient : System.ServiceModel.ClientBase<CustomerCampaign.SOAP.IRewardService>, CustomerCampaign.SOAP.IRewardService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RewardServiceClient() : 
                base(RewardServiceClient.GetDefaultBinding(), RewardServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRewardService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RewardServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RewardServiceClient.GetBindingForEndpoint(endpointConfiguration), RewardServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RewardServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RewardServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RewardServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RewardServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RewardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CustomerCampaign.SOAP.AddCustomerRewardRs> AddCustomerRewardAsync(CustomerCampaign.SOAP.AddCustomerRewardRq rq)
        {
            return base.Channel.AddCustomerRewardAsync(rq);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRewardService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRewardService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7030/RewardService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RewardServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRewardService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RewardServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRewardService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRewardService,
        }
    }
}
