//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewardService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Requests")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.GetRewardsRq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.GetRewardsForAgentRq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.GetRewardForCustomerRq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.AddRewardRq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.UpdateRewardRq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.DeleteRewardRq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.GetRewardByIdRq))]
    public partial class RequestBase : object
    {
        
        private string AuthTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthToken
        {
            get
            {
                return this.AuthTokenField;
            }
            set
            {
                this.AuthTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRewardsRq", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Requests")]
    public partial class GetRewardsRq : RewardService.RequestBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRewardsForAgentRq", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Requests")]
    public partial class GetRewardsForAgentRq : RewardService.RequestBase
    {
        
        private int AgentIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId
        {
            get
            {
                return this.AgentIdField;
            }
            set
            {
                this.AgentIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRewardForCustomerRq", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Requests")]
    public partial class GetRewardForCustomerRq : RewardService.RequestBase
    {
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddRewardRq", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Requests")]
    public partial class AddRewardRq : RewardService.RequestBase
    {
        
        private int AgentIdField;
        
        private int CustomerIdField;
        
        private decimal DiscountPercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId
        {
            get
            {
                return this.AgentIdField;
            }
            set
            {
                this.AgentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                this.DiscountPercentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateRewardRq", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Requests")]
    public partial class UpdateRewardRq : RewardService.RequestBase
    {
        
        private int AgentIdField;
        
        private int CustomerIdField;
        
        private decimal DiscountPercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId
        {
            get
            {
                return this.AgentIdField;
            }
            set
            {
                this.AgentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                this.DiscountPercentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteRewardRq", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Requests")]
    public partial class DeleteRewardRq : RewardService.RequestBase
    {
        
        private int AgentIdField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId
        {
            get
            {
                return this.AgentIdField;
            }
            set
            {
                this.AgentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRewardByIdRq", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Requests")]
    public partial class GetRewardByIdRq : RewardService.RequestBase
    {
        
        private int AgentIdField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId
        {
            get
            {
                return this.AgentIdField;
            }
            set
            {
                this.AgentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.GetRewardsRs))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.AddRewardRs))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.UpdateRewardRs))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.DeleteRewardRs))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RewardService.GetRewardRs))]
    public partial class ResponseBase : object
    {
        
        private string ErrorMessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRewardsRs", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    public partial class GetRewardsRs : RewardService.ResponseBase
    {
        
        private RewardService.Reward[] RewardsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RewardService.Reward[] Rewards
        {
            get
            {
                return this.RewardsField;
            }
            set
            {
                this.RewardsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddRewardRs", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    public partial class AddRewardRs : RewardService.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateRewardRs", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    public partial class UpdateRewardRs : RewardService.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteRewardRs", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    public partial class DeleteRewardRs : RewardService.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRewardRs", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    public partial class GetRewardRs : RewardService.ResponseBase
    {
        
        private RewardService.Reward RewardField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RewardService.Reward Reward
        {
            get
            {
                return this.RewardField;
            }
            set
            {
                this.RewardField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reward", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.Infrastructure.Models.Co" +
        "mmon")]
    public partial class Reward : object
    {
        
        private int AgentIdField;
        
        private string AgentNameField;
        
        private System.DateTime CreatedDateField;
        
        private int CustomerIdField;
        
        private string CustomerNameField;
        
        private string CustomerSsnField;
        
        private decimal DiscountPercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId
        {
            get
            {
                return this.AgentIdField;
            }
            set
            {
                this.AgentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentName
        {
            get
            {
                return this.AgentNameField;
            }
            set
            {
                this.AgentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSsn
        {
            get
            {
                return this.CustomerSsnField;
            }
            set
            {
                this.CustomerSsnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                this.DiscountPercentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RewardService.IRewardService")]
    public interface IRewardService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRewardService/GetRewardById", ReplyAction="http://tempuri.org/IRewardService/GetRewardByIdResponse")]
        System.Threading.Tasks.Task<RewardService.GetRewardRs> GetRewardByIdAsync(RewardService.GetRewardByIdRq rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRewardService/GetRewards", ReplyAction="http://tempuri.org/IRewardService/GetRewardsResponse")]
        System.Threading.Tasks.Task<RewardService.GetRewardsRs> GetRewardsAsync(RewardService.GetRewardsRq rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRewardService/GetRewardsForAgent", ReplyAction="http://tempuri.org/IRewardService/GetRewardsForAgentResponse")]
        System.Threading.Tasks.Task<RewardService.GetRewardsRs> GetRewardsForAgentAsync(RewardService.GetRewardsForAgentRq rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRewardService/GetRewardForCustomer", ReplyAction="http://tempuri.org/IRewardService/GetRewardForCustomerResponse")]
        System.Threading.Tasks.Task<RewardService.GetRewardRs> GetRewardForCustomerAsync(RewardService.GetRewardForCustomerRq rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRewardService/AddReward", ReplyAction="http://tempuri.org/IRewardService/AddRewardResponse")]
        System.Threading.Tasks.Task<RewardService.AddRewardRs> AddRewardAsync(RewardService.AddRewardRq rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRewardService/UpdateReward", ReplyAction="http://tempuri.org/IRewardService/UpdateRewardResponse")]
        System.Threading.Tasks.Task<RewardService.UpdateRewardRs> UpdateRewardAsync(RewardService.UpdateRewardRq rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRewardService/DeleteReward", ReplyAction="http://tempuri.org/IRewardService/DeleteRewardResponse")]
        System.Threading.Tasks.Task<RewardService.DeleteRewardRs> DeleteRewardAsync(RewardService.DeleteRewardRq rq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IRewardServiceChannel : RewardService.IRewardService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class RewardServiceClient : System.ServiceModel.ClientBase<RewardService.IRewardService>, RewardService.IRewardService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RewardServiceClient() : 
                base(RewardServiceClient.GetDefaultBinding(), RewardServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRewardService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RewardServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RewardServiceClient.GetBindingForEndpoint(endpointConfiguration), RewardServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RewardServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RewardServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RewardServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RewardServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RewardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RewardService.GetRewardRs> GetRewardByIdAsync(RewardService.GetRewardByIdRq rq)
        {
            return base.Channel.GetRewardByIdAsync(rq);
        }
        
        public System.Threading.Tasks.Task<RewardService.GetRewardsRs> GetRewardsAsync(RewardService.GetRewardsRq rq)
        {
            return base.Channel.GetRewardsAsync(rq);
        }
        
        public System.Threading.Tasks.Task<RewardService.GetRewardsRs> GetRewardsForAgentAsync(RewardService.GetRewardsForAgentRq rq)
        {
            return base.Channel.GetRewardsForAgentAsync(rq);
        }
        
        public System.Threading.Tasks.Task<RewardService.GetRewardRs> GetRewardForCustomerAsync(RewardService.GetRewardForCustomerRq rq)
        {
            return base.Channel.GetRewardForCustomerAsync(rq);
        }
        
        public System.Threading.Tasks.Task<RewardService.AddRewardRs> AddRewardAsync(RewardService.AddRewardRq rq)
        {
            return base.Channel.AddRewardAsync(rq);
        }
        
        public System.Threading.Tasks.Task<RewardService.UpdateRewardRs> UpdateRewardAsync(RewardService.UpdateRewardRq rq)
        {
            return base.Channel.UpdateRewardAsync(rq);
        }
        
        public System.Threading.Tasks.Task<RewardService.DeleteRewardRs> DeleteRewardAsync(RewardService.DeleteRewardRq rq)
        {
            return base.Channel.DeleteRewardAsync(rq);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRewardService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRewardService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7030/RewardService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RewardServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRewardService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RewardServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRewardService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRewardService,
        }
    }
}
