//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ReadPurchasesReportRs))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.WritePurchasesReportRs))]
    public partial class ResponseBase : object
    {
        
        private string ErrorMessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReadPurchasesReportRs", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    public partial class ReadPurchasesReportRs : ReportService.ResponseBase
    {
        
        private ReportService.PurchaseItem[] PurchaseItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReportService.PurchaseItem[] PurchaseItems
        {
            get
            {
                return this.PurchaseItemsField;
            }
            set
            {
                this.PurchaseItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WritePurchasesReportRs", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.SOAP.Models.Responses")]
    public partial class WritePurchasesReportRs : ReportService.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseItem", Namespace="http://schemas.datacontract.org/2004/07/CustomerCampaign.Infrastructure.Models.Co" +
        "mmon")]
    public partial class PurchaseItem : object
    {
        
        private string CustomerNameField;
        
        private System.DateTime PurchaseDateField;
        
        private System.Nullable<decimal> PurchaseDiscountField;
        
        private System.Nullable<decimal> PurchaseDiscountedTotalPriceField;
        
        private int PurchaseIdField;
        
        private int PurchaseItemAmountField;
        
        private int PurchaseItemIdField;
        
        private string PurchaseItemNameField;
        
        private decimal PurchaseItemUnitPriceField;
        
        private decimal PurchaseOriginalTotalPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PurchaseDate
        {
            get
            {
                return this.PurchaseDateField;
            }
            set
            {
                this.PurchaseDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PurchaseDiscount
        {
            get
            {
                return this.PurchaseDiscountField;
            }
            set
            {
                this.PurchaseDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PurchaseDiscountedTotalPrice
        {
            get
            {
                return this.PurchaseDiscountedTotalPriceField;
            }
            set
            {
                this.PurchaseDiscountedTotalPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseId
        {
            get
            {
                return this.PurchaseIdField;
            }
            set
            {
                this.PurchaseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseItemAmount
        {
            get
            {
                return this.PurchaseItemAmountField;
            }
            set
            {
                this.PurchaseItemAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseItemId
        {
            get
            {
                return this.PurchaseItemIdField;
            }
            set
            {
                this.PurchaseItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseItemName
        {
            get
            {
                return this.PurchaseItemNameField;
            }
            set
            {
                this.PurchaseItemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchaseItemUnitPrice
        {
            get
            {
                return this.PurchaseItemUnitPriceField;
            }
            set
            {
                this.PurchaseItemUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchaseOriginalTotalPrice
        {
            get
            {
                return this.PurchaseOriginalTotalPriceField;
            }
            set
            {
                this.PurchaseOriginalTotalPriceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportService")]
    public interface IReportService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/WriteCSVPurchasesReport", ReplyAction="http://tempuri.org/IReportService/WriteCSVPurchasesReportResponse")]
        System.Threading.Tasks.Task<ReportService.WritePurchasesReportRs> WriteCSVPurchasesReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ReadCSVPurchasesReport", ReplyAction="http://tempuri.org/IReportService/ReadCSVPurchasesReportResponse")]
        System.Threading.Tasks.Task<ReportService.ReadCSVPurchasesReportResponse> ReadCSVPurchasesReportAsync(ReportService.ReadCSVPurchasesReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadCSVPurchasesReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCSVPurchasesReport", Namespace="http://tempuri.org/", Order=0)]
        public ReportService.ReadCSVPurchasesReportRequestBody Body;
        
        public ReadCSVPurchasesReportRequest()
        {
        }
        
        public ReadCSVPurchasesReportRequest(ReportService.ReadCSVPurchasesReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadCSVPurchasesReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] file;
        
        public ReadCSVPurchasesReportRequestBody()
        {
        }
        
        public ReadCSVPurchasesReportRequestBody(byte[] file)
        {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadCSVPurchasesReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCSVPurchasesReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public ReportService.ReadCSVPurchasesReportResponseBody Body;
        
        public ReadCSVPurchasesReportResponse()
        {
        }
        
        public ReadCSVPurchasesReportResponse(ReportService.ReadCSVPurchasesReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadCSVPurchasesReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ReportService.ReadPurchasesReportRs ReadCSVPurchasesReportResult;
        
        public ReadCSVPurchasesReportResponseBody()
        {
        }
        
        public ReadCSVPurchasesReportResponseBody(ReportService.ReadPurchasesReportRs ReadCSVPurchasesReportResult)
        {
            this.ReadCSVPurchasesReportResult = ReadCSVPurchasesReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IReportServiceChannel : ReportService.IReportService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<ReportService.IReportService>, ReportService.IReportService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReportServiceClient() : 
                base(ReportServiceClient.GetDefaultBinding(), ReportServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IReportService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReportServiceClient.GetBindingForEndpoint(endpointConfiguration), ReportServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReportServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReportServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ReportService.WritePurchasesReportRs> WriteCSVPurchasesReportAsync()
        {
            return base.Channel.WriteCSVPurchasesReportAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportService.ReadCSVPurchasesReportResponse> ReportService.IReportService.ReadCSVPurchasesReportAsync(ReportService.ReadCSVPurchasesReportRequest request)
        {
            return base.Channel.ReadCSVPurchasesReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportService.ReadCSVPurchasesReportResponse> ReadCSVPurchasesReportAsync(byte[] file)
        {
            ReportService.ReadCSVPurchasesReportRequest inValue = new ReportService.ReadCSVPurchasesReportRequest();
            inValue.Body = new ReportService.ReadCSVPurchasesReportRequestBody();
            inValue.Body.file = file;
            return ((ReportService.IReportService)(this)).ReadCSVPurchasesReportAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReportService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReportService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7030/ReportService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReportServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IReportService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReportServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IReportService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IReportService,
        }
    }
}
